import {
  ChefHat,
  Zap,
  Leaf,
  Heart
} from "lucide-react";

const FeatureBar = () => {
  const features = [
    {
      icon: <ChefHat />,
      title: "AI Powered",
      text: "Smart recipes generated by AI"
    },
    {
      icon: <Zap />,
      title: "Quick & Easy",
      text: "Save time with easy step-by-step recipes"
    },
    {
      icon: <Leaf />,
      title: "Personalized",
      text: "Recipes tailored to your ingredients & taste"
    },
    {
      icon: <Heart />,
      title: "Save & Share",
      text: "Save your favorites and share with loved ones"
    }
  ];

  return (
    <div className="card bg-base-100 border border-base-200 shadow-sm mt-8">

      <div className="card-body">

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">

          {features.map((feature) => (
            <div
              key={feature.title}
              className="flex items-center gap-4"
            >

              <div className="w-12 h-12 rounded-full bg-orange-50 flex items-center justify-center text-orange-500">
                {feature.icon}
              </div>

              <div>
                <h3 className="font-semibold">
                  {feature.title}
                </h3>

                <p className="text-sm text-gray-500">
                  {feature.text}
                </p>
              </div>

            </div>
          ))}

        </div>

      </div>
    </div>
  );
};

export default FeatureBar;